name: mskim.org
#description: Blog
meta_description: "Blog"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mskim.org'
google_analytics: 'UA-97982726-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://mskim.org'
author:         'mskimm'
